export const CONTACTS_CHANGE_NAME = "CONTACTS_CHANGE_NAME";
export const CONTACTS_CHANGE_EMAIL = 'CONTACTS_CHANGE_EMAIL';
export const CONTACTS_CHANGE_QUESTION = 'CONTACTS_CHANGE_QUESTION';
export const CONTACTS_SUBMIT = 'CONTACTS_SUBMIT';