export const HANDLE_FILLING = "HANDLE_FILLING";
export const HANDLE_WEIGHT_1 = 'HANDLE_WEIGHT_1';
export const HANDLE_WEIGHT_2 = 'HANDLE_WEIGHT_2';
export const HANDLE_WEIGHT_5 = 'HANDLE_WEIGHT_5';
export const HANDLE_WEIGHT_8 = 'HANDLE_WEIGHT_8';
export const HANDLE_CHOISE_BERRY = 'HANDLE_CHOISE_BERRY';
export const HANDLE_CHOISE_MARSHMALLOW = 'HANDLE_CHOISE_MARSHMALLOW';
